config/routes.rb
Rails.application.routes.draw do
    get 'booking', :to => "booking#index"
    get 'contact', :to => "contact#index"
    get 'about', :to => "about#index"

    root 'welcome#index'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def copyright_notice_year_range(start_year)
      # In case the input was not a number (nil.to_i will return a 0)
      start_year = start_year.to_i

      # Get the current year from the system
      current_year = Time.new.year

      # When the current year is more recent than the start year, return a string 
      # of a range (e.g., 2010 - 2012). Alternatively, as long as the start year 
      # is reasonable, return it as a string. Otherwise, return the current year 
      # from the system.
      if current_year > start_year && start_year > 2000
        "#{start_year} - #{current_year}"
      elsif start_year > 2000
        "#{start_year}"
      else
        "#{current_year}"
      end
    end
    

end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
    <!-- Page Title
            ============================================= -->
            <section id="page-title" class="page-title-parallax page-title-dark" style="padding: 250px 0; background-image: url('<%= asset_path('about/parallax.jpg') %>'); background-size: cover; background-position: center center;" data-stellar-background-ratio="0.4">



                <div class="container clearfix">
                    <h1 data-animate="fadeInUp">Our Story</h1>
                    <span data-animate="fadeInUp" data-delay="200">Everything you need to know.</span>   
                </div>

            </section><!-- #page-title end -->

<div class="divider divider-short divider-center topmargin-sm"><i class="icon-camera"></i></div>

        <!-- Content
        ============================================= -->
        <section id="content">

            <div class="content-wrap">

                 <div class="row common-height clearfix">

                    <div class="col-sm-5 col-padding" style="background: url('<%= asset_path('about/about.jpg') %>') center center no-repeat; background-size: cover;"></div>

                    <div class="col-sm-7 col-padding">
                        <div>
                            <div class="heading-block">
                                <span class="before-heading color">Owners</span>
                                <h3>Sivan &amp; Craig Rettew</h3>
                            </div>

                            <div class="row clearfix">

                                <div class="col-md-12">
                                    <p>Studio Adorn was founded in 2013 by us, Sivan & Craig, owners of <%= link_to("Sivan Photography", "http://www.sivanphotography.com", target: "_blank") %>. After searching for rental space for boudoir photos and having no luck, we decided to not only open a studio for our own use, but to rent it out to other photographers who need it just as much as we do.</p> 
                                    
                                    <p>We were sitting at our favorite coffee shop (Axum in Winter Garden) discussing the details of a boudoir studio, it truly seemed unattainable. We talked about all of the amazing details that Sivan had envisioned. She wanted a huge, open space with no walls, and with dark wood floors. She wanted there to be floor-to-ceiling windows, and all on the 2nd floor so that her boudoir lovelies could feel more comfortable. We looked around on the surface, but decided it wasn&#8217;t the time. Besides, could we ever really find a space like that in Orlando? Sivan pictured a New York ballet studio. Elegant, classy, romantic.</p>

                                    <p>One day, after a boudoir bash, Sivan couldn&#8217;t take it anymore. Her excitement was through the roof, and so we started driving all over Winter Garden and Ocoee looking for &#8220;space available&#8221; signs. Just as she was about to give up and head home, she thought &#8220;let me turn into this one last plaza and see if there&#8217;s anything.&#8221; We had no idea our dream space was literally walking distance from our house. It had everything we wanted!</p>
                                    
                                    <p>In no time we decided to lease the space and renovate it. It took about a month of hard work to get it to where it is today. Our goal is to provide photographers a unique space to let their imaginations flourish. With endless combinations of setups, you and your client will be more than pleased with the one-of-a-kind final product! This space is truly a photographer's playground.</p>

                                    </div>

                            </div>

                        </div>
                    </div>

                </div>

                

                </div>

            

        </section><!-- #content end -->

<iframe src="//player.vimeo.com/video/88479092?color=ff5546&amp;title=0&amp;byline=0&amp;portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

<div class="divider divider-short divider-center topmargin-sm"><i class="icon-camera"></i></div>

app/views/booking/index.html.erb
<!-- Page Title
        ============================================= -->
        <section id="page-title" class="page-title-parallax page-title-dark" style="padding: 250px 0; background-image: url('<%= asset_path('booking/booking.jpg') %>'); background-size: cover; background-position: center center;" data-stellar-background-ratio="0.4">

            
                
            <div class="container clearfix">
                <h1 data-animate="fadeInUp">Booking the Studio</h1>
                <span data-animate="fadeInUp" data-delay="200">Booking our studio is easy.</span>   
            </div>

        </section><!-- #page-title end -->

 <section id="content">

    <div class="content-wrap nobottompadding">                        
        <div class="heading-block center" data-animate="fadeIn">
            <h2>By the Hour</h2>                        
        </div>

            <div class="container clearfix">

                <div class="pricing bottommargin clearfix">

                    <div class="col-sm-6">

                        <div class="pricing-box">
                            <div class="pricing-title">
                                <h3>Weekday (Mon-Thurs)</h3>
                            </div>
                            <div class="pricing-price">
                                <span class="price-unit">&dollar;</span>95<span class="price-tenure">for first 2 hours (min)</span>
                            </div>
                            <div class="pricing-features">
                                <ul>
                                    <li><h3>$50 per hour for additional time</h3></li>
                                </ul>
                            </div>

                        </div>

                    </div>

                 <div class="col-sm-6">

                        <div class="pricing-box">
                            <div class="pricing-title">
                                <h3>Weekend (Fri-Sun)</h3>
                            </div>
                            <div class="pricing-price">
                                <span class="price-unit">&dollar;</span>109<span class="price-tenure">for first 2 hours (min)</span>
                            </div>
                            <div class="pricing-features">
                                <ul>
                                    <li><h3>$60 per hour for additional time</h3></li>
                                </ul>
                            </div>

                        </div>

                    </div>


                </div>
            </div>
                    
                                            



            <div class="container clearfix">
                        
                <div class="heading-block center" data-animate="fadeIn">
                    <h2>Memberships</h2>                        
                </div>

                <div class="pricing bottommargin clearfix">
                                                
                    <div class="col-md-4">

                        <div class="pricing-box">
                            <div class="pricing-title">
                                <h3>Starter</h3>
                            </div>
                            <div class="pricing-price">
                                <span class="price-unit">&dollar;</span>295<span class="price-tenure">/mo</span>
                            </div>
                            <div class="pricing-features">
                                <ul>
                                    <li><strong>8</strong> hours per month</li>
                                    <li>(Over <strong>&dollar;170</strong> in savings)</li>
                                </ul>
                            </div>
                        </div>

                    </div>

                    <div class="col-md-4">

                        <div class="pricing-box best-price">
                            <div class="pricing-title">
                                <h3>Pro</h3>
                                <span>Most Popular</span>
                            </div>
                            <div class="pricing-price">
                                <span class="price-unit">&dollar;</span>355<span class="price-tenure">/mo</span>
                            </div>
                            <div class="pricing-features">
                                <ul>
                                    <li><strong>12</strong> hours per month</li>
                                    <li>(Over <strong>&dollar;350</strong> in savings)</li>
                                </ul>
                            </div>
                        </div>

                    </div>

                    <div class="col-md-4">

                        <div class="pricing-box">
                            <div class="pricing-title">
                                <h3>Deluxe</h3>
                            </div>
                            <div class="pricing-price">
                                <span class="price-unit">&dollar;</span>425<span class="price-tenure">/mo</span>
                            </div>
                            <div class="pricing-features">
                                <ul>
                                    <li><strong>16</strong> hours per month</li>
                                    <li>(Over <strong>&dollar;520</strong> in savings)</li>
                                </ul>
                            </div>
                        </div>

                    </div>
                    
                    

                </div>
                <div class="center">
                    <p>*All memberships require a 3 month commitment</br>
                    *All rentals are a minimum of 2 hours</p>
                </div>
                    
             </div>
        
                    <div class="promo parallax promo-dark promo-flat promo-full bottommargin" style="background-image: url('<%= asset_path('booking/booking.jpg') %>');" data-stellar-background-ratio="0.5">
                <div class="container clearfix">
                    <h3>Send us a booking request below and we'll send you a booking center.</h3>
                    <span>Book your boudoir, newborn, portrait, headshots, or any type of session at Studio Adorn today!</span>
                    <a href="#calendar" data-href="#calendar" class="button button-reveal button-xlarge"><i class="icon-angle-right"></i><span>Book Now</span></a>
                </div>
            </div>

    </div>

</section><!-- #content end -->

            
            
            
            
<section id="content">

    <div class="content-wrap nobottompadding">

            <div class="heading-block center" data-animate="fadeIn">
                <h2>Booking Process</h2>

            </div>

            <div class="container clearfix">

                <div class="col_half">
                    <div class="feature-box fbox-effect nobottomborder" data-animate="fadeIn">
                        <h3>Booking Studio Adorn</h3>
                        <ul>
                            <li>Check availability via our calendar below.</li>
                            <li>Select the number of hours you'd like to book, followed by the day and start time.</li>
                            <li>We will review your selection and send a booking center with invoices and a contract within 24 hours.</li>
                            <li>A contract &amp; 50% retainer is required to reserve your date and time slot.</li>
                            <li>An incidental fee will be required before the commencement of your reservation and will be refunded after the date of booking.</li>

                        </ul>
                    </div>
                </div>

                <div class="col_half col_last">
                    <div class="feature-box fbox-effect nobottomborder" data-animate="fadeIn">
                        <h3>During Your Rental</h3>
                        <ul>
                            <li>A Studio Adorn representative will let you in 15 minutes before your booked time.</li>
                            <li>We will walk through the studio with you to ensure everything is in order before your session. Your signature will officially start your reservation and the studio is all yours!</li>
                            <li>At the end of your booked time, we'll to do a final walk-through to ensure that everything ran smoothly.</li>

                        </ul>
                    </div>
                </div>
                

                
            </div>
        
            <div class="center" data-animate="fadeIn">
                <p>*Studio Adorn requires all photographers to provide proof of identity.</p>
            </div>
 </section>
    
<section id="calendar">
    <div class="content-wrap">
        <div class="heading-block center" data-animate="fadeIn">
                <h2>Booking Calendar</h2>
        </div>
    
        <div align="center" style="height:100%;margin:auto;">
            <iframe src="//secure.scheduleonce.com/studioadorn&thm=white&dt=&em=1" id="SOI_studioadorn" name="ScheduleOnceIframe"  scrolling="no" frameborder="0" hspace="0" marginheight="0" marginwidth="0" height="635px" width="100% !important" vspace="0" style="max-width: 796px;width:100% !important;border-radius: 7px;-webkit-border-radius:7px;"></iframe>
        </div>
        
        <script type="text/javascript" src="//secure.scheduleonce.com/mergedjs/ScheduleOnceEmbed.js"></script><script type="text/javascript">soe.AddEventListners();</script>
    
    
    </div>
    
    
    
</section>
     
     

app/views/contact/index.html.erb
<!-- Document Wrapper
    ============================================= -->
    <div id="wrapper" class="clearfix">

        <!-- Contact Form & Map Overlay Section
        ============================================= -->
        <section id="map-overlay">

            <div class="container clearfix">

                <!-- Contact Form Overlay
                ============================================= -->
                <div id="contact-form-overlay-mini" class="clearfix">

                    <div class="fancy-title title-dotted-border">
                        <h3>Send us an Email</h3>
                    </div>

                    <div id="contact-form-result" data-notify-type="success" data-notify-msg="<i class=icon-ok-sign></i> Message Sent Successfully!"></div>

                    <!-- Contact Form
                    ============================================= -->
                    <form class="nobottommargin" id="template-contactform" name="template-contactform" action="include/sendemail.php" method="post">

                        <div class="col_full">
                            <label for="template-contactform-name">Name <small>*</small></label>
                            <input type="text" id="template-contactform-name" name="template-contactform-name" value="" class="sm-form-control required" />
                        </div>

                        <div class="col_full">
                            <label for="template-contactform-email">Email <small>*</small></label>
                            <input type="email" id="template-contactform-email" name="template-contactform-email" value="" class="required email sm-form-control" />
                        </div>

                        <div class="clear"></div>

                        <div class="col_full">
                            <label for="template-contactform-message">Message <small>*</small></label>
                            <textarea class="required sm-form-control" id="template-contactform-message" name="template-contactform-message" rows="6" cols="30"></textarea>
                        </div>

                        <div class="col_full hidden">
                            <input type="text" id="template-contactform-botcheck" name="template-contactform-botcheck" value="" class="sm-form-control" />
                        </div>

                        <div class="col_full">
                            <button class="button button-3d nomargin" type="submit" id="template-contactform-submit" name="template-contactform-submit" value="submit">Send Message</button>
                        </div>

                    </form>

                    <script type="text/javascript">
                        $("#template-contactform").validate({
                            submitHandler: function(form) {
                                $('.form-process').fadeIn();
                                $(form).ajaxSubmit({
                                    target: '#contact-form-result',
                                    success: function() {
                                        $('.form-process').fadeOut();
                                        $('#template-contactform').find('.sm-form-control').val('');
                                        $('#contact-form-result').attr('data-notify-msg', $('#contact-form-result').html()).html('');
                                        SEMICOLON.widget.notifications($('#contact-form-result'));
                                    }
                                });
                            }
                        });
                    </script>

                </div><!-- Contact Form Overlay End -->

            </div>

            <!-- Google Map
            ============================================= -->
            <section id="google-map" class="gmap">
            
            <iframe src="https://www.google.com/maps/embed?pb=!1m0!3m2!1sen!2sus!4v1421883369757!6m8!1m7!1sA3fX5rehtbYAAAQZLDKYmA!2m2!1d28.528674!2d-81.541259!3f124.81632511373215!4f-17.885487828264914!5f0.7820865974627469" width=100% height=100% frameborder="0" style="border:0"></iframe>
                
            </section>


        </section><!-- Contact Form & Map Overlay Section End -->

app/views/layouts/_footer.html.erb
<!-- Footer
============================================= -->
<footer id="footer" class="dark">
    <div id="copyrights">
        <div class="container clearfix">
            <div class="col_one_third">
                
                <%= link_to("http://www.facebook.com/studioadorn", class: "social-icon si-dark si-colored si-facebook nobottommargin center", style: "margin-right: 10px", target: "_blank") do %>
                    <i class="icon-facebook"></i> 
                    <i class="icon-facebook"></i>
                    <%= t(:show).html_safe %>
                <% end %>

                <%= link_to("http://www.instagram.com/studioadorn", class: "social-icon si-dark si-colored si-instagram nobottommargin", style: "margin-right: 10px", target: "_blank") do %>
                    <i class="icon-instagram"></i> 
                    <i class="icon-instagram"></i>
                    <%= t(:show).html_safe %>
                <% end %>

                <%= link_to("http://plus.google.com/studioadorn", class: "social-icon si-dark si-colored si-gplus nobottommargin", style: "margin-right: 10px", target: "_blank") do %>
                    <i class="icon-gplus"></i> 
                    <i class="icon-gplus"></i>
                    <%= t(:show).html_safe %>
                <% end %></br></br>
                
                &copy; <%= copyright_notice_year_range(2013) %> Studio Adorn. All Rights Reserved.
                    <div class="copyright-links"><a href="#">Terms of Use</a> / <a href="#">Privacy Policy</a></div>
            </div>

            <div class="col_one_third">

                <i class="icon-envelope2"></i> info@studioadorn.com</br>
                <i class="icon-headphones"></i> 321.345.9231</br>
                <i class="icon-globe"></i> 2910 S. Maguire Road Suite 2011 Ocoee, FL 34761</br>
                <i class="icon-clock"></i> Open from 8am - 8pm Everyday (by appt only)
            </div>

            <div class="col_one_third col_last">
                <div class="fright clearfix">
                     <div class="widget subscribe-widget clearfix">
                        <h5><strong>Subscribe</strong> to Our Newsletter to get Important News, Amazing Offers &amp; Inside Scoops:</h5>
                        <div id="widget-subscribe-form-result" data-notify-type="success" data-notify-msg=""></div>
                        <form id="widget-subscribe-form" action="include/subscribe.php" role="form" method="post" class="nobottommargin">
                            <div class="input-group divcenter">
                                <span class="input-group-addon"><i class="icon-email2"></i></span>
                                <input type="email" id="widget-subscribe-form-email" name="widget-subscribe-form-email" class="form-control required email" placeholder="Enter your Email">
                                <span class="input-group-btn">
                                    <button class="btn btn-success" type="submit">Subscribe</button>
                                </span>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div><!-- #copyrights end -->

</footer><!-- #footer end -->

<!-- Go To Top
============================================= -->
<div id="gotoTop" class="icon-angle-up"></div>

app/views/layouts/_header.html.erb
<div id="header-trigger"><i class="icon-line-menu"></i><i class="icon-line-cross"></i></div>

    <!-- Header
    ============================================= -->
    <header id="header" class="no-sticky">

        <div id="header-wrap">

            <div class="container clearfix">

                <div id="primary-menu-trigger"><i class="icon-reorder"></i></div>

                <!-- Logo
                ============================================= -->
                <div id="logo" class="nobottomborder">
                    <%= link_to(image_tag('logo.png'), root_path, class: "standard-logo") %>
                    <%= link_to(image_tag('logo@2x.png'), root_path, class: "retina-logo") %>
                </div><!-- #logo end -->

                <!-- Primary Navigation
                ============================================= -->
                <nav id="primary-menu">

                    <ul>
                        <li>
                            <%= link_to("Home", root_path) %>                           
                        </li>
                        <li>
                            <%= link_to("Our Story", about_path) %>
                        </li>
                        <li>
                            <%= link_to("Adorn Blog", root_path) %>
                        </li>
                        <li>
                            <%= link_to("Studio Rental", booking_path) %>
                        </li>
                        <li>
                            <%= link_to("Get in Touch", contact_path) %>
                        </li>
                    </ul>

                </nav><!-- #primary-menu end -->

                <div class="clearfix visible-md visible-lg">
                    
                    <%= link_to("http://www.facebook.com/studioadorn", class: "social-icon si-small si-borderless si-facebook", target: "_blank") do %>
                        <i class="icon-facebook"></i> 
                        <i class="icon-facebook"></i>                    
                    <% end %>

                    
                    <%= link_to("http://www.instagram.com/studioadorn", class: "social-icon si-small si-borderless si-instagram", target: "_blank") do %>
                        <i class="icon-instagram"></i>
                        <i class="icon-instagram"></i>
                    <% end %>
                    
                    <%= link_to("https://plus.google.com/u/0/b/116502175131665083122/116502175131665083122", class: "social-icon si-small si-borderless si-gplus", target: "_blank") do %>
                        <i class="icon-gplus"></i>
                        <i class="icon-gplus"></i>
                    <% end %>

                </div>

            </div>

        </div>

    </header><!-- #header end -->